// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";
import { normalizePostgresSslMode } from "./src/lib/postgres-url";

const rawUrl = process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"];

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "bun prisma/seed.ts",
  },
  datasource: {
    // Neon: use DIRECT_URL for migrate/push when available (non-pooled).
    url: rawUrl ? normalizePostgresSslMode(rawUrl) : rawUrl,
  },
});
